---
# Update pbgui, pb6 and pb7 on localhost
# Steps:
# 1. Clone pbgui repository
# 2. Restart PBRun, PBRemote and PBCoinData if pbgui repository was updated
# 3. Clone passivbot repository for pb6
# 4. Restart all pb6 bots if pb6 repository was updated
# 5. Clone passivbot repository for pb7
# 6. Restart all pb7 bots if pb7 repository was updated

- hosts: localhost
  gather_facts: "{{ debug }}"

  vars:
    # ansible_ssh_pass: "{{ user_pw }}"
    # ansible_become_password: "{{ user_pw }}"
    user: "{{ user }}"
    pbgdir: "{{ pbgdir }}"
    pb6dir: "{{ pb6dir }}"
    pb7dir: "{{ pb7dir }}"
    pb7venv: "{{ pb7venv }}"
    # user_pw: "{{ user_pw }}"

  tasks:
    - name: display facts
      debug:
        var: ansible_facts
      tags: debug,never

    - name: Update rust
      command: rustup update stable
      register: update_rust

    - name: print update_rust
      debug:
        var: update_rust
      tags: debug,never

    - name: clone pbgui repository
      git:
        repo: https://github.com/msei99/pbgui.git
        dest: "{{ pbgdir }}"
        version: main
        update: yes
        force: yes
      when: pbgdir != ""
      register: pbgui_repo
      notify: restart pbgui

    - name: print pbgui_repo
      debug:
        var: pbgui_repo
      tags: debug,never

    - name: clone passivbot repository for pb6
      git:
        repo: https://github.com/enarjord/passivbot.git
        dest: "{{ pb6dir }}"
        version: v6.1.4b_latest_v6
        update: yes
        force: yes
      when: pb6dir != ""
      register: pb6_repo
      notify: restart pb6

    - name: print pb6_repo
      debug:
        var: pb6_repo
      tags: debug,never

    - name: clone passivbot repository for pb7
      git:
        repo: https://github.com/enarjord/passivbot.git
        dest: "{{ pb7dir }}"
        version: master
        update: yes
        force: yes
      when: pb7dir != ""
      register: pb7_repo
      notify: restart pb7

    - name: print pb7_repo
      debug:
        var: pb7_repo
      tags: debug,never

  handlers:
    - name: Install pbgui requirements
      pip:
        requirements: "{{ pbgdir }}/requirements.txt"
        extra_args: --upgrade pip
      listen: "restart pbgui"

    - name: Restart PBRun, PBRemote and PBCoinData
      shell: |
        python "{{ pbgdir }}/starter.py" -r PBRun PBRemote PBCoinData
      args:
        executable: /bin/bash
        chdir: "{{ pbgdir }}"
      listen: "restart pbgui"

    - name: Install pb6 requirements
      pip:
        virtualenv: "{{ pb6venv }}"
        requirements: "{{ pb6dir }}/requirements.txt"
        extra_args: --upgrade pip
      listen: "restart pb6"

    - name: kill all pb6 processes
      shell: "kill $(ps -ef | grep {{ pb6dir }}/passivbot | grep -v grep | awk '{print $2}')"
      listen: "restart pb6"
      ignore_errors: yes

    - name: Make sure PBRun ist running
      shell: |
        python "{{ pbgdir }}/starter.py" -s PBRun
      args:
        executable: /bin/bash
        chdir: "{{ pbgdir }}"
      listen: "restart pb6"

    - name: Install pb7 requirements
      pip:
        virtualenv: "{{ pb7venv }}"
        requirements: "{{ pb7dir }}/requirements.txt"
        extra_args: --upgrade pip
      listen: "restart pb7"

    - name: Build passivbot-rust with maturin
      shell: |
        source "{{ pb7venv }}/bin/activate"
        maturin develop --release
      args:
        chdir: "{{ pb7dir }}/passivbot-rust"
        executable: /bin/bash
      register: maturin_result
      listen: "restart pb7"

    - name: kill all pb7 processes
      shell: "kill $(ps -ef | grep {{ pb7dir }}/src/main.py | grep -v grep | awk '{print $2}')"
      listen: "restart pb7"
      ignore_errors: yes
    
    - name: Make sure PBRun ist running
      shell: |
        python "{{ pbgdir }}/starter.py" -s PBRun
      args:
        executable: /bin/bash
        chdir: "{{ pbgdir }}"
      listen: "restart pb7"
