---
# Recreate PB7 venv with Python 3.12 on localhost (Master)
# Steps:
# 1. Stop PBRun + PBRemote
# 2. Kill running pb7 processes (bots + workers)
# 3. Install python3.12-venv
# 4. Remove old venv_pb7
# 5. Update pb7 repository (keep current branch)
# 6. Create new python3.12 venv for pb7 + install requirements (upgrade pip)
# 7. Build passivbot-rust with maturin
# 8. Start PBRun
# 9. Start PBRun + PBRemote

- hosts: localhost
  gather_facts: "{{ debug }}"

  vars:
    ansible_become_password: "{{ user_pw }}"
    user: "{{ user }}"
    user_pw: "{{ user_pw }}"
    pbgdir: "{{ pbgdir }}"
    pb7dir: "{{ pb7dir }}"
    pb7venv: "{{ pb7venv }}"

  tasks:
    - name: display facts
      debug:
        var: ansible_facts
      tags: debug,never

    - name: Stop PBRun + PBRemote
      shell: |
        python "{{ pbgdir }}/starter.py" -k PBRun PBRemote
      args:
        executable: /bin/bash
        chdir: "{{ pbgdir }}"
      when: pbgdir != ""
      ignore_errors: yes

    - name: kill all pb7 processes (bots)
      shell: "kill $(ps -ef | grep {{ pb7dir }}/src/main.py | grep -v grep | awk '{print $2}')"
      when: pb7dir != ""
      ignore_errors: yes

    - name: kill all pb7 processes (workers using pb7 venv)
      shell: "kill $(ps -ef | grep {{ pb7venv }}/bin/python | grep -v grep | awk '{print $2}')"
      when: pb7venv != ""
      ignore_errors: yes

    - name: Install software-properties-common (for PPAs)
      apt:
        pkg:
          - software-properties-common
        update_cache: yes
      become: yes

    - name: Add deadsnakes/ppa
      apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present
        update_cache: yes
      become: yes

    - name: Install python3.12-venv
      apt:
        pkg:
          - python3.12-venv
        update_cache: yes
        clean: yes
      become: yes

    - name: Remove old pb7 venv
      file:
        path: "{{ pb7venv }}"
        state: absent
      when: pb7venv != ""
      become: yes

    - name: Get current pb7 branch
      command: git rev-parse --abbrev-ref HEAD
      args:
        chdir: "{{ pb7dir }}"
      register: current_pb7_branch
      changed_when: false
      when: pb7dir != ""

    - name: update passivbot repository for pb7 (keep current branch)
      git:
        repo: https://github.com/enarjord/passivbot.git
        dest: "{{ pb7dir }}"
        version: "{{ current_pb7_branch.stdout }}"
        update: yes
        force: yes
      when: pb7dir != ""
      register: pb7_repo

    - name: print pb7_repo
      debug:
        var: pb7_repo
      tags: debug,never

    - name: create python3.12 venv for pb7
      pip:
        virtualenv_command: python3.12 -m venv
        virtualenv: "{{ pb7venv }}"
        requirements: "{{ pb7dir }}/requirements.txt"
        extra_args: --upgrade pip
      when: pb7dir != "" and pb7venv != ""

    - name: Build passivbot-rust with maturin
      shell: |
        source ~/.profile || source ~/.bashrc || true
        source "{{ pb7venv }}/bin/activate"
        maturin develop --release
      args:
        chdir: "{{ pb7dir }}/passivbot-rust"
        executable: /bin/bash
      when: pb7dir != "" and pb7venv != ""
      register: maturin_result

    - name: print maturin result
      debug:
        var: maturin_result
      tags: debug,never

    - name: Start PBRun + PBRemote
      shell: |
        python "{{ pbgdir }}/starter.py" -s PBRun PBRemote
      args:
        executable: /bin/bash
        chdir: "{{ pbgdir }}"
      when: pbgdir != ""
