---
# Update pbgui, pb6 and pb7 on localhost
# Steps:
# 1. Clone pbgui repository
# 2. Restart PBRun, PBRemote and PBCoinData if pbgui repository was updated
# 3. Clone passivbot repository for pb6
# 4. Restart all pb6 bots if pb6 repository was updated
# 5. Clone passivbot repository for pb7
# 6. Restart all pb7 bots if pb7 repository was updated

- hosts: localhost
  gather_facts: "{{ debug }}"

  vars:
    # ansible_ssh_pass: "{{ user_pw }}"
    # ansible_become_password: "{{ user_pw }}"
    user: "{{ user }}"
    pbgdir: "{{ pbgdir }}"
    pbgvenv: "{{ pbgvenv }}"
    pb6dir: "{{ pb6dir }}"
    pb7dir: "{{ pb7dir }}"
    pb7venv: "{{ pb7venv }}"
    # user_pw: "{{ user_pw }}"

  tasks:
    - name: display facts
      debug:
        var: ansible_facts
      tags: debug,never

    - name: remove stable toolchain if exists
      shell: rustup toolchain uninstall stable 1.78.0
      args:
        executable: /bin/bash
      ignore_errors: yes

    - name: Update rust
      shell: rustup update 1.90.0
      args:
        executable: /bin/bash
      register: update_rust

    - name: print update_rust
      debug:
        var: update_rust
      tags: debug,never

    - name: clone passivbot repository for pb6
      git:
        repo: https://github.com/enarjord/passivbot.git
        dest: "{{ pb6dir }}"
        version: v6.1.4b_latest_v6
        update: yes
        force: yes
      when: pb6dir != ""
      register: pb6_repo
      notify: restart pb6

    - name: print pb6_repo
      debug:
        var: pb6_repo
      tags: debug,never

    - name: Get current pb7 branch
      command: git rev-parse --abbrev-ref HEAD
      args:
        chdir: "{{ pb7dir }}"
      register: current_pb7_branch
      changed_when: false
      when: pb7dir != ""

    - name: clone passivbot repository for pb7
      git:
        repo: https://github.com/enarjord/passivbot.git
        dest: "{{ pb7dir }}"
        version: "{{ current_pb7_branch.stdout }}"
        update: yes
        force: yes
      when: pb7dir != ""
      register: pb7_repo
      notify: restart pb7

    - name: print pb7_repo
      debug:
        var: pb7_repo
      tags: debug,never

  handlers:
    - name: Install pb6 requirements
      pip:
        virtualenv: "{{ pb6venv }}"
        requirements: "{{ pb6dir }}/requirements.txt"
        extra_args: --upgrade pip
      listen: "restart pb6"

    - name: kill all pb6 processes
      shell: "kill $(ps -ef | grep {{ pb6dir }}/passivbot | grep -v grep | awk '{print $2}')"
      listen: "restart pb6"
      ignore_errors: yes

    - name: Make sure PBRun ist running
      shell: |
        python "{{ pbgdir }}/starter.py" -s PBRun
      args:
        executable: /bin/bash
        chdir: "{{ pbgdir }}"
      listen: "restart pb6"

    - name: Install pb7 requirements
      pip:
        virtualenv: "{{ pb7venv }}"
        requirements: "{{ pb7dir }}/requirements.txt"
        extra_args: --upgrade pip
      listen: "restart pb7"

    - name: Build passivbot-rust with maturin
      shell: |
        source "{{ pb7venv }}/bin/activate"
        maturin develop --release
      args:
        chdir: "{{ pb7dir }}/passivbot-rust"
        executable: /bin/bash
      register: maturin_result
      listen: "restart pb7"

    - name: kill all pb7 processes
      shell: "kill $(ps -ef | grep {{ pb7dir }}/src/main.py | grep -v grep | awk '{print $2}')"
      listen: "restart pb7"
      ignore_errors: yes
    
    - name: Make sure PBRun ist running
      shell: |
        python "{{ pbgdir }}/starter.py" -s PBRun
      args:
        executable: /bin/bash
        chdir: "{{ pbgdir }}"
      listen: "restart pb7"
