---
# Recreate PB7 venv with Python 3.12 on localhost (Master)
# Steps:
# 1. Stop PBRun + PBRemote
# 2. Kill running pb7 processes (bots + workers)
# 3. Install python3.12-venv
# 4. Remove old venv_pb7
# 5. Update pb7 repository (keep current branch)
# 6. Create new python3.12 venv for pb7 + install requirements (upgrade pip)
# 7. Build passivbot-rust with maturin
# 8. Start PBRun
# 9. Start PBRun + PBRemote

- hosts: localhost
  gather_facts: "{{ debug }}"

  vars:
    ansible_become_password: "{{ user_pw }}"
    user: "{{ user }}"
    user_pw: "{{ user_pw }}"
    pbgdir: "{{ pbgdir }}"
    pb7dir: "{{ pb7dir }}"
    pb7venv: "{{ pb7venv }}"

  tasks:
    - name: display facts
      debug:
        var: ansible_facts
      tags: debug,never

    - name: Stop PBRun + PBRemote
      shell: |
        python "{{ pbgdir }}/starter.py" -k PBRun PBRemote
      args:
        executable: /bin/bash
        chdir: "{{ pbgdir }}"
      when: pbgdir != ""
      ignore_errors: yes

    - name: Detect OS + arch (for Ubuntu 20.04 x86_64 uv path)
      shell: |
        set -euo pipefail
        . /etc/os-release
        echo "${ID:-unknown} ${VERSION_ID:-unknown}"
        uname -m
      args:
        executable: /bin/bash
      register: os_arch
      changed_when: false

    - name: Set use_uv_python312 flag (Ubuntu 20.04 + x86_64)
      set_fact:
        use_uv_python312: >-
          {{ (os_arch.stdout_lines[0].startswith('ubuntu 20.04'))
             and (os_arch.stdout_lines[1] == 'x86_64') }}
        uv_bin: "{{ lookup('env', 'HOME') }}/.local/bin/uv"
      changed_when: false

    - name: kill all pb7 processes (bots)
      shell: "kill $(ps -ef | grep {{ pb7dir }}/src/main.py | grep -v grep | awk '{print $2}')"
      when: pb7dir != ""
      ignore_errors: yes

    - name: kill all pb7 processes (workers using pb7 venv)
      shell: "kill $(ps -ef | grep {{ pb7venv }}/bin/python | grep -v grep | awk '{print $2}')"
      when: pb7venv != ""
      ignore_errors: yes

    - name: Install python3.12-venv
      apt:
        pkg:
          - python3.12-venv
        update_cache: yes
        clean: yes
      become: yes
      when: not (use_uv_python312 | default(false))

    - name: Install curl + ca-certificates for uv (Ubuntu 20.04 x86_64)
      apt:
        pkg:
          - curl
          - ca-certificates
        update_cache: yes
        clean: yes
      become: yes
      when: use_uv_python312 | default(false)

    - name: Install uv (Ubuntu 20.04 x86_64)
      shell: |
        set -euo pipefail
        curl -LsSf https://astral.sh/uv/install.sh | sh
      args:
        executable: /bin/bash
        creates: "{{ uv_bin }}"
      when: use_uv_python312 | default(false)

    - name: Install Python 3.12 via uv (Ubuntu 20.04 x86_64)
      shell: |
        set -euo pipefail
        "{{ uv_bin }}" python install 3.12
      args:
        executable: /bin/bash
      register: uv_python_install
      changed_when: uv_python_install.rc == 0 and (uv_python_install.stdout | default('')) != ''
      when: use_uv_python312 | default(false)

    - name: Remove old pb7 venv
      file:
        path: "{{ pb7venv }}"
        state: absent
      when: pb7venv != ""
      become: yes

    - name: Get current pb7 branch
      command: git rev-parse --abbrev-ref HEAD
      args:
        chdir: "{{ pb7dir }}"
      register: current_pb7_branch
      changed_when: false
      when: pb7dir != ""

    - name: update passivbot repository for pb7 (keep current branch)
      git:
        repo: https://github.com/enarjord/passivbot.git
        dest: "{{ pb7dir }}"
        version: "{{ current_pb7_branch.stdout }}"
        update: yes
        force: yes
      when: pb7dir != ""
      register: pb7_repo

    - name: print pb7_repo
      debug:
        var: pb7_repo
      tags: debug,never

    - name: Create python3.12 venv for PB7 (apt python3.12)
      pip:
        virtualenv_command: python3.12 -m venv
        virtualenv: "{{ pb7venv }}"
        requirements: "{{ pb7dir }}/requirements.txt"
        extra_args: --upgrade pip
      when: (not (use_uv_python312 | default(false))) and pb7dir != "" and pb7venv != ""

    - name: Create python3.12 venv for PB7 (uv Python 3.12 on Ubuntu 20.04 x86_64)
      shell: |
        set -euo pipefail
        "{{ uv_bin }}" venv --python 3.12 "{{ pb7venv }}"
      args:
        executable: /bin/bash
        creates: "{{ pb7venv }}/bin/activate"
      when: (use_uv_python312 | default(false)) and pb7dir != "" and pb7venv != ""

    - name: Install PB7 requirements into uv venv
      pip:
        requirements: "{{ pb7dir }}/requirements.txt"
        executable: "{{ pb7venv }}/bin/pip"
        extra_args: --upgrade pip
      when: (use_uv_python312 | default(false)) and pb7dir != "" and pb7venv != ""

    - name: Build passivbot-rust with maturin
      shell: |
        source ~/.profile || source ~/.bashrc || true
        source "{{ pb7venv }}/bin/activate"
        maturin develop --release
      args:
        chdir: "{{ pb7dir }}/passivbot-rust"
        executable: /bin/bash
      when: pb7dir != "" and pb7venv != ""
      register: maturin_result

    - name: print maturin result
      debug:
        var: maturin_result
      tags: debug,never

    - name: Start PBRun + PBRemote
      shell: |
        python "{{ pbgdir }}/starter.py" -s PBRun PBRemote
      args:
        executable: /bin/bash
        chdir: "{{ pbgdir }}"
      when: pbgdir != ""
