---
# Switch pb7 branch/commit on localhost
# Steps:
# 1. Fetch from origin
# 2. Check for uncommitted changes (fail if found)
# 3. Checkout specified branch
# 4. Optionally checkout specific commit (detached HEAD)
# 5. Pull if on branch HEAD (not detached)
# 6. Restart pbgui services

- hosts: localhost
  gather_facts: "{{ debug }}"

  vars:
    user: "{{ user }}"
    pbgdir: "{{ pbgdir }}"
    pbgvenv: "{{ pbgvenv }}"
    pb7dir: "{{ pb7dir }}"
    pb7venv: "{{ pb7venv }}"
    target_branch: "{{ pb7_branch }}"
    target_commit: "{{ pb7_commit | default('') }}"

  tasks:
    - name: display facts
      debug:
        var: ansible_facts
      tags: debug,never

    - name: Fetch from origin
      command: git fetch origin
      args:
        chdir: "{{ pb7dir }}"
      when: pb7dir != ""
      changed_when: false

    - name: Check for uncommitted changes (tracked files only)
      shell: git diff --name-only && git diff --cached --name-only
      args:
        chdir: "{{ pb7dir }}"
      register: git_status
      changed_when: false

    - name: Fail if uncommitted changes exist
      fail:
        msg: "Uncommitted changes detected in PB7. Please commit or stash changes before switching branches."
      when: git_status.stdout != ""

    - name: Checkout target branch
      command: git checkout "{{ target_branch }}"
      args:
        chdir: "{{ pb7dir }}"
      register: checkout_result
      notify: restart pb7

    - name: Reset to specific commit if provided (stays on branch)
      command: git reset --hard "{{ target_commit }}"
      args:
        chdir: "{{ pb7dir }}"
      when: target_commit != ""
      register: commit_reset
      notify: restart pb7

    - name: Pull latest changes (only if no specific commit provided)
      command: git pull
      args:
        chdir: "{{ pb7dir }}"
      when: target_commit == ""
      register: pull_result
      notify: restart pb7

    - name: Display checkout result
      debug:
        msg: |
          PB7 Branch: {{ target_branch }}
          PB7 Commit: {{ target_commit if target_commit != '' else 'HEAD' }}
          Status: Switched successfully
      tags: debug,never

  handlers:
    - name: Install pb7 requirements
      pip:
        requirements: "{{ pb7dir }}/requirements.txt"
        virtualenv: "{{ pb7venv }}"
        extra_args: --upgrade pip
      listen: "restart pb7"

    - name: Build passivbot-rust with maturin
      shell: |
        source "{{ pb7venv }}/bin/activate"
        maturin develop --release
      args:
        chdir: "{{ pb7dir }}/passivbot-rust"
        executable: /bin/bash
      register: maturin_result
      listen: "restart pb7"

    - name: kill all pb7 processes
      shell: "kill $(ps -ef | grep {{ pb7dir }}/src/main.py | grep -v grep | awk '{print $2}')"
      listen: "restart pb7"
      ignore_errors: yes

    - name: Make sure PBRun ist running
      shell: |
        python "{{ pbgdir }}/starter.py" -s PBRun
      args:
        executable: /bin/bash
        chdir: "{{ pbgdir }}"
      listen: "restart pb7"
