---
# Update pbgui, pb6 and pb7
# Steps:
# 1. Clone pbgui repository
# 2. Restart PBRun, PBRemote and PBCoinData if pbgui repository was updated

- hosts: "{{ hostname }}"
  gather_facts: yes

  vars:
    # ansible_ssh_pass: "{{ user_pw }}"
    # ansible_become_password: "{{ user_pw }}"
    user: "{{ user }}"
    # user_pw: "{{ user_pw }}"

  tasks:
    - name: display facts
      debug:
        var: ansible_facts
      tags: debug,never

    - name: get install_dir
      set_fact:
        install_dir: "{{ ansible_env.HOME + '/software' }}"

    - name: Get current branch
      command: git rev-parse --abbrev-ref HEAD
      args:
        chdir: "{{ install_dir }}/pbgui"
      register: current_branch
      changed_when: false

    - name: clone pbgui repository
      git:
        repo: https://github.com/msei99/pbgui.git
        dest: "{{ install_dir }}/pbgui"
        version: "{{ current_branch.stdout }}"
        update: yes
        force: yes
      register: pbgui_repo
      notify: restart pbgui

    - name: print pbgui_repo
      debug:
        var: pbgui_repo
      tags: debug,never

  handlers:
    - name: Install pbgui requirements
      pip:
        virtualenv: "{{ install_dir }}/venv_pbgui"
        requirements: "{{ install_dir }}/pbgui/requirements_vps.txt"
        extra_args: --upgrade pip
      listen: "restart pbgui"

    - name: Restart PBRun, PBRemote and PBCoinData
      shell: |
        source "{{ install_dir }}/venv_pbgui/bin/activate"
        python "{{ install_dir }}/pbgui/starter.py" -r PBRun PBRemote PBCoinData
      args:
        executable: /bin/bash
        chdir: "{{ install_dir }}/pbgui"
      listen: "restart pbgui"

    - name: Verify PBRun PBRemote and PBCoinData are running
      shell: |
        source "{{ install_dir }}/venv_pbgui/bin/activate"
        missing=0
        for proc in PBRun.py PBRemote.py PBCoinData.py; do
          if ! pgrep -f "{{ install_dir }}/pbgui/${proc}" >/dev/null; then
            echo "Missing process: ${proc}"
            python "{{ install_dir }}/pbgui/starter.py" -s "${proc%.py}" || true
            missing=1
          fi
        done
        if [ "$missing" -ne 0 ]; then
          echo "--- PBRun.log tail ---"
          tail -n 40 "{{ install_dir }}/pbgui/data/logs/PBRun.log" || true
          echo "--- PBRemote.log tail ---"
          tail -n 40 "{{ install_dir }}/pbgui/data/logs/PBRemote.log" || true
          echo "--- PBCoinData.log tail ---"
          tail -n 40 "{{ install_dir }}/pbgui/data/logs/PBCoinData.log" || true
          exit 1
        fi
      args:
        executable: /bin/bash
        chdir: "{{ install_dir }}/pbgui"
      register: pbgui_process_health
      retries: 8
      delay: 3
      until: pbgui_process_health.rc == 0
      listen: "restart pbgui"
