---
# Update CoinData API key on VPS
# Steps:
# 1. Update pbgui.ini with new API key
# 2. Restart pbgui service

- hosts: "{{ hostname }}"
  gather_facts: yes

  vars:
    # ansible_ssh_pass: "{{ user_pw }}"
    ansible_become_password: "{{ user_pw }}"
    user: "{{ user }}"
    api_key: "{{ coinmarketcap_api_key }}"
    reboot: "{{ reboot }}"
    install_dir: "{{ install_dir | default(ansible_facts['env']['HOME'] + '/software') }}"

  tasks:
    - name: display facts
      debug:
        var: ansible_facts
      tags: debug,never

    - name: print install_dir
      debug:
        var: install_dir
      tags: debug,never

    - name: Change CoinMarketCap API key 
      ini_file:
        path: "{{ install_dir }}/pbgui/pbgui.ini"
        section: coinmarketcap
        option: api_key
        value: "{{ api_key }}"

    - name: Start or Restart PBRun, PBRemote and PBCoinData
      script: setup/vps_service_control.sh restart PBRun PBRemote PBCoinData
      environment:
        PBGUI_DIR: "{{ install_dir }}/pbgui"
        PBGUI_PYTHON: "{{ install_dir }}/venv_pbgui/bin/python"
        PBGUI_USER: "{{ user }}"
      register: pbgui_process_health
      retries: 8
      delay: 3
      until: pbgui_process_health.rc == 0

    - name: print service control result
      debug:
        var: pbgui_process_health
      tags: debug,never
