---
# Recreate PB7 venv with Python 3.12 on a VPS
# Steps:
# 1. Stop PBRun + PBRemote
# 2. Kill running PB7 processes (bots + workers)
# 3. Install python3.12-venv
# 4. Remove old venv_pb7
# 5. Update pb7 repository (keep current branch)
# 6. Create new python3.12 venv for pb7 + install requirements (upgrade pip)
# 7. Build passivbot-rust with maturin
# 8. Start PBRun + PBRemote

- hosts: "{{ hostname }}"
  gather_facts: true

  vars:
    ansible_become_password: "{{ user_pw }}"
    user: "{{ user }}"

  tasks:
    - name: display facts
      debug:
        var: ansible_facts
      tags: debug,never

    - name: get install_dir
      set_fact:
        install_dir: "{{ ansible_user_dir }}/software"

    - name: Stop PBRun + PBRemote
      shell: |
        source "{{ install_dir }}/venv_pbgui/bin/activate"
        python "{{ install_dir }}/pbgui/starter.py" -k PBRun PBRemote
      args:
        executable: /bin/bash
        chdir: "{{ install_dir }}/pbgui"
      ignore_errors: yes

    - name: kill all pb7 processes (bots)
      shell: |
        pids="$(ps -ef | grep "{{ install_dir }}/pb7/src/main.py" | grep -v grep | awk '{print $2}')"
        if [ -n "$pids" ]; then
          kill $pids
        fi
      args:
        executable: /bin/bash
      changed_when: false
      ignore_errors: yes

    - name: kill all pb7 processes (workers using pb7 venv)
      shell: |
        pids="$(ps -ef | grep "{{ install_dir }}/venv_pb7/bin/python" | grep -v grep | awk '{print $2}')"
        if [ -n "$pids" ]; then
          kill $pids
        fi
      args:
        executable: /bin/bash
      changed_when: false
      ignore_errors: yes

    - name: Install python3.12-venv
      apt:
        pkg:
          - python3.12-venv
        update_cache: yes
        clean: yes
      become: yes

    - name: Remove old pb7 venv
      file:
        path: "{{ install_dir }}/venv_pb7"
        state: absent
      become: yes

    - name: Get current pb7 branch
      command: git rev-parse --abbrev-ref HEAD
      args:
        chdir: "{{ install_dir }}/pb7"
      register: current_pb7_branch
      changed_when: false

    - name: update passivbot repository for pb7 (keep current branch)
      git:
        repo: https://github.com/enarjord/passivbot.git
        dest: "{{ install_dir }}/pb7"
        version: "{{ current_pb7_branch.stdout }}"
        update: yes
        force: yes
      register: pb7_repo

    - name: print pb7_repo
      debug:
        var: pb7_repo
      tags: debug,never

    - name: create python3.12 venv for pb7
      pip:
        virtualenv_command: python3.12 -m venv
        virtualenv: "{{ install_dir }}/venv_pb7"
        requirements: "{{ install_dir }}/pb7/requirements.txt"
        extra_args: --upgrade pip

    - name: Build passivbot-rust with maturin
      shell: |
        source ~/.profile || source ~/.bashrc || true
        source "{{ install_dir }}/venv_pb7/bin/activate"
        maturin develop --release
      args:
        chdir: "{{ install_dir }}/pb7/passivbot-rust"
        executable: /bin/bash
      register: maturin_result

    - name: print maturin result
      debug:
        var: maturin_result
      tags: debug,never

    - name: Start PBRun + PBRemote
      shell: |
        source "{{ install_dir }}/venv_pbgui/bin/activate"
        python "{{ install_dir }}/pbgui/starter.py" -s PBRun PBRemote
      args:
        executable: /bin/bash
        chdir: "{{ install_dir }}/pbgui"
