---
# Update CoinData API key on VPS
# Steps:
# 1. Update pbgui.ini with new API key
# 2. Restart pbgui service

- hosts: "{{ hostname }}"
  gather_facts: yes

  vars:
    # ansible_ssh_pass: "{{ user_pw }}"
    ansible_become_password: "{{ user_pw }}"
    user: "{{ user }}"
    api_key: "{{ coinmarketcap_api_key }}"
    reboot: "{{ reboot }}"

  tasks:
    - name: display facts
      debug:
        var: ansible_facts
      tags: debug,never

    - name: get remote_home and install_dir
      set_fact:
        remote_home: "{{ ansible_env.HOME }}"
        install_dir: "{{ ansible_env.HOME + '/software' }}"
    
    - name: print install_dir
      debug:
        var: install_dir
      tags: debug,never

    - name: Change CoinMarketCap API key 
      ini_file:
        path: "{{ install_dir }}/pbgui/pbgui.ini"
        section: coinmarketcap
        option: api_key
        value: "{{ api_key }}"

    - name: Start or Restart PBRun and PBRemote
      shell: |
        source "{{ install_dir }}/venv_pbgui/bin/activate"
        python "{{ install_dir }}/pbgui/starter.py" -r PBRun PBRemote
      args:
        executable: /bin/bash
        chdir: "{{ install_dir }}/pbgui"
      register: starter_result

    - name: print starter result
      debug:
        var: starter_result
      tags: debug,never

    - name: Start or Restart PBCoinData
      shell: |
        source "{{ install_dir }}/venv_pbgui/bin/activate"
        python "{{ install_dir }}/pbgui/starter.py" -r PBCoinData
      args:
        executable: /bin/bash
        chdir: "{{ install_dir }}/pbgui"
      register: starter_result

    - name: Verify PBRun PBRemote and PBCoinData are running
      shell: |
        source "{{ install_dir }}/venv_pbgui/bin/activate"
        missing=0
        for proc in PBRun.py PBRemote.py PBCoinData.py; do
          if ! pgrep -f "{{ install_dir }}/pbgui/${proc}" >/dev/null; then
            echo "Missing process: ${proc}"
            python "{{ install_dir }}/pbgui/starter.py" -s "${proc%.py}" || true
            missing=1
          fi
        done
        if [ "$missing" -ne 0 ]; then
          echo "--- PBRun.log tail ---"
          tail -n 40 "{{ install_dir }}/pbgui/data/logs/PBRun.log" || true
          echo "--- PBRemote.log tail ---"
          tail -n 40 "{{ install_dir }}/pbgui/data/logs/PBRemote.log" || true
          echo "--- PBCoinData.log tail ---"
          tail -n 40 "{{ install_dir }}/pbgui/data/logs/PBCoinData.log" || true
          exit 1
        fi
      args:
        executable: /bin/bash
        chdir: "{{ install_dir }}/pbgui"
      register: pbgui_process_health
      retries: 8
      delay: 3
      until: pbgui_process_health.rc == 0

    - name: print starter result
      debug:
        var: starter_result
      tags: debug,never
