---
# Switch pbgui branch/commit on VPS
# Steps:
# 1. Fetch from origin
# 2. Check for uncommitted changes (fail if found)
# 3. Checkout specified branch
# 4. Optionally checkout specific commit (detached HEAD)
# 5. Pull if on branch HEAD (not detached)
# 6. Restart pbgui services

- hosts: "{{ hostname }}"
  gather_facts: yes

  vars:
    user: "{{ user }}"
    target_branch: "{{ branch }}"
    target_commit: "{{ commit | default('') }}"

  tasks:
    - name: display facts
      debug:
        var: ansible_facts
      tags: debug,never

    - name: get install_dir
      set_fact:
        install_dir: "{{ ansible_env.HOME + '/software' }}"
        pbgdir: "{{ ansible_env.HOME + '/software/pbgui' }}"

    - name: Fetch from origin
      command: git fetch origin
      args:
        chdir: "{{ pbgdir }}"
      changed_when: false

    - name: List all remote branches for debugging
      command: git branch -r
      args:
        chdir: "{{ pbgdir }}"
      register: remote_branches
      changed_when: false
      tags: debug,never

    - name: Display remote branches
      debug:
        var: remote_branches.stdout_lines
      tags: debug,never

    - name: Check for uncommitted changes (tracked files only)
      shell: git diff --name-only && git diff --cached --name-only
      args:
        chdir: "{{ pbgdir }}"
      register: git_status
      changed_when: false

    - name: Fail if uncommitted changes exist
      fail:
        msg: "Uncommitted changes detected. Please commit or stash changes before switching branches."
      when: git_status.stdout != ""

    - name: Check if branch exists on remote
      shell: git ls-remote --heads origin "{{ target_branch }}" | wc -l
      args:
        chdir: "{{ pbgdir }}"
      register: remote_branch_exists
      changed_when: false

    - name: Fail if branch doesn't exist on remote
      fail:
        msg: "Branch '{{ target_branch }}' does not exist on remote 'origin'. Please push the branch first."
      when: remote_branch_exists.stdout == "0"

    - name: Check if branch exists locally
      command: git rev-parse --verify "{{ target_branch }}"
      args:
        chdir: "{{ pbgdir }}"
      register: branch_exists
      failed_when: false
      changed_when: false

    - name: Create and checkout local branch from remote if it doesn't exist
      command: git checkout -b "{{ target_branch }}" --track "origin/{{ target_branch }}"
      args:
        chdir: "{{ pbgdir }}"
      when: branch_exists.rc != 0
      register: checkout_new
      notify: restart pbgui

    - name: Checkout target branch (if already exists locally)
      command: git checkout "{{ target_branch }}"
      args:
        chdir: "{{ pbgdir }}"
      when: branch_exists.rc == 0
      register: checkout_result
      notify: restart pbgui

    - name: Checkout specific commit if provided
      command: git checkout "{{ target_commit }}"
      args:
        chdir: "{{ pbgdir }}"
      when: target_commit != ""
      register: commit_checkout
      notify: restart pbgui

    - name: Pull latest changes (only if on branch HEAD, not detached)
      command: git pull
      args:
        chdir: "{{ pbgdir }}"
      when: target_commit == ""
      register: pull_result
      notify: restart pbgui

    - name: Display checkout result
      debug:
        msg: |
          Branch: {{ target_branch }}
          Commit: {{ target_commit if target_commit != '' else 'HEAD' }}
          Status: Switched successfully
      tags: debug,never

  handlers:
    - name: Install pbgui requirements
      pip:
        virtualenv: "{{ install_dir }}/venv_pbgui"
        requirements: "{{ install_dir }}/pbgui/requirements_vps.txt"
        extra_args: --upgrade pip
      listen: "restart pbgui"

    - name: Restart PBRun, PBRemote and PBCoinData
      shell: |
        source "{{ install_dir }}/venv_pbgui/bin/activate"
        python "{{ install_dir }}/pbgui/starter.py" -r PBRun PBRemote PBCoinData
      args:
        executable: /bin/bash
        chdir: "{{ install_dir }}/pbgui"
      listen: "restart pbgui"
